spring:
 h2.console:
  enabled: true
  path: '/console'
 datasource:
  url: 'jdbc:h2:C:/Users/Patryk/Downloads/FastRace/race-db'
 jpa:
   hibernate:
     ddl-auto: validate
 flyway:
   baseline-on-migrate: on
   hibernate:
     dialect=org:
       hibernate:
         dialect: H2Dialect
